---
- hosts: db
  become: yes
  tasks:
  - name: mariadb-server install
    yum: name=mariadb-server state=present
  - name: Ensure MariaDB is running
    service: name=mariadb state=started enabled=yes  
  - name: Modify ipTables for MariaDB
    # Equiv -a: iptables -A INPUT -s 192.168.60.0/24 -p tcp -m tcp --dport 3306 -j ACCEPT
    iptables: chain=INPUT source=192.168.60.0/24 protocol=tcp match=tcp destination_port=3306 jump=ACCEPT
  - name: mysql-python via yum
    yum: name=MySQL-python state=present
  - name: Create MySQL User "django"
    mysql_user: name=django host=% password=12345 priv=*.*:ALL state=present